import os
from pathlib import Path

DISCORD_TOKEN = os.getenv("TOKEN", None)
assert DISCORD_TOKEN is not None, "MISSING DISCORD_TOKEN"

CREDENTIALS_FILENAME = "credentials.json"
assert Path.exists(CREDENTIALS_FILENAME), "MISSING CREDENTIALS FILE"

SHEET_SHIFT_SIGNUPS = os.getenv("SHEET_SHIFT_SIGNUPS", None)
SHEET_SHIFT_SIGNUPS_SIGNUPS_TAB = "Sign Up"
assert SHEET_SHIFT_SIGNUPS is not None, "MISSING SHEET_SHIFT_SIGNUPS"

SHEET_DISCORD_MEMBERS = os.getenv("SHEET_DISCORD_MEMBERS", None)
SHEET_DISCORD_MEMBERS_VOLUNTEERS_TAB = "SYF"
SHEET_DISCORD_MEMBERS_ID_COL = 0
SHEET_DISCORD_MEMBERS_NAME_COL = 1
SHEET_DISCORD_MEMBERS_NICKNAME_COL = 3
assert SHEET_DISCORD_MEMBERS is not None, "MISSING SHEET_DISCORD_MEMBERS"

SHIFT_VALIDATION_WEBHOOK_ID = 1337111947551703142


# Function, not a constant. Needs to evaluate at run-time.
def get_cog_files():
    return os.listdir("./cogs")
